sidecar:
  image:
    # -- The Docker registry
    registry: ghcr.io
    repository: kiwigrid/k8s-sidecar
    tag: 1.30.3

image:
  registry: docker.io
  repository: grafana/grafana
  tag: 11.6.1

initChownData:
  image:
    registry: docker.io
    repository: library/busybox
    tag: 1.37.0

downloadDashboardsImage:
  registry: docker.io
  repository: curlimages/curl
  tag: 8.13.0
