name: Publish UDS Core

on:
  push:
    branches:
      - main

jobs:
  tag-new-version:
    name: Tag New Version
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-flag.outputs.release_created }}
    steps:
      - name: Create release tag
        id: tag
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4
        with:
          command: manifest # use configs in release-please-config.json
      - id: release-flag
        run: echo "release_created=${{ steps.tag.outputs.release_created || false }}" >> $GITHUB_OUTPUT

  publish-uds-core:
    strategy:
      matrix:
        flavor: [upstream, registry1]
    needs: tag-new-version
    if: ${{ needs.tag-new-version.outputs.release_created == 'true'}}
    runs-on: ubuntu-latest
    name: Publish packages

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Environment setup
        uses: ./.github/actions/setup
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          ib_user: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          ib_password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Publish UDS Zarf Package
        run: uds run -f tasks/publish.yaml packages --set FLAVOR=${{ matrix.flavor }}

      - name: Publish UDS Bundles
        run: uds run -f tasks/publish.yaml bundles --set FLAVOR=${{ matrix.flavor }}

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
