name: Test Upgrade of UDS Core

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      flavor:
        type: string
        description: "Flavor of the core package to test"
        required: true
  # Triggered by pull-request-conditionals.yaml
  workflow_call:
    inputs:
      flavor:
        type: string
        description: "Flavor of the core package to test"
        required: true

permissions:
  contents: read

jobs:
  test-upgrade:
    runs-on: "uds-ubuntu-big-boy-8-core"
    timeout-minutes: 30
    name: Test Upgrade

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Environment setup
        uses: ./.github/actions/setup
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          ib_user: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          ib_password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Test upgrade
        run: uds run test-uds-core-upgrade --set FLAVOR=${{ inputs.flavor }}

      - name: Debug Output
        if: ${{ !cancelled() }}
        run: |
          kubectl get all -A
          kubectl get package -A

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
